using System.Collections;
using System.Collections.Generic;
using UnityEngine;

    /// <summary>
    /// Enumeration of config data names
    /// </summary>
public enum ConfigDataName
{
    Heart,
    PickupRange,
    SmallXpOrb,
    MediumXpOrb,
    LargeXpOrb,
    XLargeXpOrb,
    XXLargeXpOrb,
    XXXLargeXpOrb,
    EnemyHealth,
    BossHealth,
    KingHealth,
    PlayerHealth,
    PlayerMaxHealth,
    PlayerDamage,
    PlayerCritChance,
    PlayerMoveSpeed,
    PlayerSeedSpeed,
    PlayerShootCooldown,
    SeedlingHealth,
    SeedlingDamage,
    SeedlingROF,
    ThornDamage,
    ThornROF,
    ComMoveSpeedMod,
    UncMoveSpeedMod,
    RarMoveSpeedMod,
    ComShootCooldownMod,
    UncShootCooldownMod,
    RarShootCooldownMod,
    ComMaxHealthMod,
    UncMaxHealthMod,
    RarMaxHealthMod,
    ComSeedSpeedMod,
    UncSeedSpeedMod,
    RarSeedSpeedMod,
    ComCritChanceMod,
    UncCritChanceMod,
    RarCritChanceMod,
    ComDamageMod,
    UncDamageMod,
    RarDamageMod,
    UncThornDamageMod,
    RarThornDamageMod,
    UncThornROFMod,
    RarThornROFMod,
    UncSeedlingDamageMod,
    RarSeedlingDamageMod,
    UncSeedlingROFMod,
    RarSeedlingROFMod,
    UncSeedlingHealthMod,
    RarSeedlingHealthMod,
}
